name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    if: gitea.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install JS dependencies
        run: npm install
      - name: Run build
        run: npm run build
