name: Check scripts syntax
on: [push]

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup zip
        run: |
          sudo apt-get install zip -y
      - name: Install JS dependencies
        run: |
          npm install
      - name: Run scripts
        run: |
          bash download-icons.sh
      - name: Run build
        run: |
          npm run build
          zip -r vision-start.zip dist
      - name: Release zip
        uses: akkuman/gitea-release-action@v1
        with:
          name: latest
          tag_name: latest
          files: |-
            vision-start.zip
